import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from "@/shared/components/ui/toaster"


export const metadata: Metadata = {
  title: 'TabTune Animator',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6346152303245774"
          crossOrigin="anonymous"></script>
        <meta name="google-adsense-account" content="ca-pub-6346152303245774"></meta>
      </head>
      <body className="font-body antialiased bg-background">

        <div>
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
