import { ChordDiagramProps } from '../domain/types';
import { getNote, getComplement, getExtension } from '../domain/chord-logic';

export const chordData: ChordDiagramProps[] = [
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('E'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 2: [2, 2], 3: [2, 3], 4: [1, 1] },
        avoid: [],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('E'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('E'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 2: [2, 2], 3: [2, 3], 4: [1, 1], 5: [3, 4] },
        avoid: [],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('E'),
        unique: true,
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('E'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 2: [2, 2], 4: [1, 1], 5: [3, 4] },
        avoid: [],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('E'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('B'), complement: getComplement('m'), extension: [getExtension('7'), getExtension('9')], bass: 0 },
        positions: { 2: [2, 2], 4: [2, 3], 5: [2, 4] },
        avoid: [1, 6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('B'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('E'), complement: getComplement('m'), extension: [getExtension('7')], bass: 0 },
        positions: { 2: [2, 2] },
        avoid: [],
        nut: { vis: true, str: [1, 6], pos: 0, fin: 1, trn: 0 },
        origin: getNote('E'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('E'), complement: getComplement('m'), extension: [getExtension('7')], bass: 0 },
        positions: { 2: [2, 2], 3: [2, 3], 5: [3, 4] },
        avoid: [],
        nut: { vis: true, str: [1, 6], pos: 0, fin: 1, trn: 0 },
        origin: getNote('E'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A'), complement: getComplement('m'), extension: [getExtension('7'), getExtension('b5')], bass: 0 },
        positions: { 3: [1, 2], 4: [0, 1], 5: [1, 3] },
        avoid: [1, 6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A'), complement: getComplement('m'), extension: [getExtension('7')], bass: 0 },
        positions: { 4: [6, 1], 5: [8, 3], 6: [9, 4] },
        avoid: [1, 3],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('F'), complement: getComplement('m'), extension: [getExtension('6')], bass: 0 },
        positions: { 1: [1, 2], 4: [1, 3], 5: [1, 4] },
        avoid: [2, 6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('F'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('F'), complement: getComplement('m'), extension: [getExtension('7')], bass: 0 },
        positions: { 1: [1, 1], 3: [1, 2], 4: [1, 3], 5: [1, 4] },
        avoid: [2, 6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('F'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A#'), complement: getComplement('m'), extension: [getExtension('7'), getExtension('b5')], bass: 0 },
        positions: { 2: [1, 2], 4: [1, 3], 5: [2, 4], 6: [0, 1] },
        avoid: [1, 3],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A#'),
    }, {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('E'), complement: getComplement('m'), extension: [getExtension('7')], bass: 0 },
        positions: { 4: [1, 1] },
        avoid: [2, 6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('E'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 3: [2, 2], 4: [2, 3], 5: [2, 1] },
        avoid: [1],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('D'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 4: [2, 1], 5: [3, 3], 6: [2, 2] },
        avoid: [1, 2],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('D'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('G'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 1: [3, 3], 2: [2, 2], 6: [3, 4] },
        avoid: [],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('G'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('F'), complement: getComplement('°'), extension: [], bass: 0 },
        positions: { 1: [1, 1], 3: [1, 2], 5: [1, 3] },
        avoid: [2, 4, 6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('F'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A'), complement: getComplement('°'), extension: [], bass: 0 },
        positions: { 2: [1, 1], 4: [2, 2], 6: [1, 3] },
        avoid: [1, 3, 5],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('D'), complement: getComplement('°'), extension: [], bass: 0 },
        positions: { 1: [1, 1], 3: [2, 2], 5: [1, 3] },
        avoid: [2, 4, 6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('D'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A'), complement: getComplement('m'), extension: [], bass: 0 },
        positions: { 2: [1, 1], 3: [2, 2], 4: [2, 3] },
        avoid: [6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A'), complement: getComplement('Major'), extension: [getExtension('sus2')], bass: 0 },
        positions: { 3: [2, 2], 4: [2, 1] },
        avoid: [6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A'),
    },
    {
        stringNames: ["E", "A", "D", "G", "B", "e"],
        chord: { note: getNote('A'), complement: getComplement('Major'), extension: [getExtension('sus4')], bass: 0 },
        positions: { 2: [3, 3], 3: [2, 2], 4: [2, 1] },
        avoid: [6],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('A'),
    },
    {
        chord: { note: getNote('E'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 1: [0, 0], 2: [2, 1], 3: [2, 2] }, // Bass E Major
        avoid: [],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('E'),
        stringNames: ["E", "A", "D", "G"]
    },
    {
        chord: { note: getNote('D'), complement: getComplement('Major'), extension: [], bass: 0 },
        positions: { 4: [0, 0], 5: [3, 2], 6: [2, 1] }, // Drop D tuning test
        avoid: [],
        nut: { vis: false, str: [0, 0], pos: 0, fin: 0, trn: 1 },
        origin: getNote('D'),
        stringNames: ["D", "A", "D", "G", "B", "e"]
    }
];
